// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFh0ezuQBqR3KFIbao2d1x-36jSTdkrc4',
    appId: '1:868647229605:web:68bd9006f2a1bf2351d54c',
    messagingSenderId: '868647229605',
    projectId: 'zoe-crochet',
    authDomain: 'zoe-crochet.firebaseapp.com',
    storageBucket: 'zoe-crochet.firebasestorage.app',
    measurementId: 'G-X7QKVC3CV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyTmhf_pQJ4f0uVSfI3adyhVddNk5kTsw',
    appId: '1:868647229605:android:bc6c0dbd09fc68fb51d54c',
    messagingSenderId: '868647229605',
    projectId: 'zoe-crochet',
    storageBucket: 'zoe-crochet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNbH4H50aAZ08mxIFf6_kCB5o1m08ERDo',
    appId: '1:868647229605:ios:0c3d4e316a29aa1f51d54c',
    messagingSenderId: '868647229605',
    projectId: 'zoe-crochet',
    storageBucket: 'zoe-crochet.firebasestorage.app',
    iosBundleId: 'com.example.zoesCrochet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNbH4H50aAZ08mxIFf6_kCB5o1m08ERDo',
    appId: '1:868647229605:ios:0c3d4e316a29aa1f51d54c',
    messagingSenderId: '868647229605',
    projectId: 'zoe-crochet',
    storageBucket: 'zoe-crochet.firebasestorage.app',
    iosBundleId: 'com.example.zoesCrochet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFh0ezuQBqR3KFIbao2d1x-36jSTdkrc4',
    appId: '1:868647229605:web:fcd8b393fdb914ec51d54c',
    messagingSenderId: '868647229605',
    projectId: 'zoe-crochet',
    authDomain: 'zoe-crochet.firebaseapp.com',
    storageBucket: 'zoe-crochet.firebasestorage.app',
    measurementId: 'G-6JHFXJEZSB',
  );
}
